import { Wand2, AlertCircle, RefreshCw, ChevronRight } from 'lucide-react'
import ComponentPreview from '../components/ComponentPreview'
import LoadingSkeleton from '../components/LoadingSkeleton'
import { useGeneration } from '../contexts/GenerationContext'
import { useToast } from '../components/ToastContainer'
import { useNavigate } from 'react-router-dom'
import { loadSettings } from '../services/api'
import { useEffect, useState } from 'react'

export default function Generator() {
  const {
    instruction,
    setInstruction,
    loading,
    result,
    error,
    clearError,
    handleGenerate,
    clearResult,
  } = useGeneration()
  
  const toast = useToast()
  const navigate = useNavigate()
  const [hasSettings, setHasSettings] = useState(false)
  const [charCount, setCharCount] = useState(0)
  const maxChars = 500
  
  useEffect(() => {
    const settings = loadSettings()
    setHasSettings(!!(settings && settings.apiKey))
  }, [])
  
  useEffect(() => {
    setCharCount(instruction.length)
  }, [instruction])
  
  const loadingVariations = [
    { id: 'loading-1', name: 'Minimalist', style: 'minimal' as const },
    { id: 'loading-2', name: 'Statement', style: 'bold' as const },
    { id: 'loading-3', name: 'Sophisticated', style: 'elegant' as const },
    { id: 'loading-4', name: 'Expressive', style: 'playful' as const },
    { id: 'loading-5', name: 'Contemporary', style: 'modern' as const },
  ]
  
  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
      e.preventDefault()
      if (!loading && instruction.trim()) {
        handleGenerate()
      }
    }
  }
  
  const handleGenerateClick = async () => {
    if (!hasSettings) {
      toast.warning('Please configure your AI settings first')
      setTimeout(() => navigate('/settings'), 1500)
      return
    }
    await handleGenerate()
  }
  
  const handleClearAndNew = () => {
    clearResult()
    setInstruction('')
  }
  
  return (
    <div className="flex flex-col min-h-[calc(100vh-12rem)] relative">
      <div className="flex-1 pb-32">
        {!loading && !result && (
          <div className="max-w-2xl mx-auto text-center mb-12 animate-fade-in">
            <h2 className="text-4xl font-bold tracking-tight mb-4">What are we building today?</h2>
            <p className="text-neutral-500">Describe your UI component and watch AI generate five distinct variations.</p>

            {!hasSettings && (
              <div className="mt-8 p-6 bg-neutral-50 rounded-3xl border border-neutral-100 inline-block text-left">
                <div className="flex items-start gap-4">
                  <AlertCircle className="w-5 h-5 text-neutral-400 mt-1" />
                  <div>
                    <p className="font-semibold text-sm">Configuration Required</p>
                    <p className="text-xs text-neutral-500 mb-4">Set up your AI provider to start generating.</p>
                    <button
                      onClick={() => navigate('/settings')}
                      className="px-4 py-2 bg-neutral-900 text-white rounded-xl text-xs font-medium hover:bg-neutral-800 transition-colors flex items-center gap-2"
                    >
                      Configure <ChevronRight className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}

        {loading ? (
          <div className="space-y-8 animate-fade-in">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-2xl font-bold">Generating variations...</h3>
                <p className="text-sm text-neutral-500">Crafting five unique designs based on your prompt.</p>
              </div>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {loadingVariations.map((v) => (
                <div key={v.id} className="h-[500px]">
                  <LoadingSkeleton name={v.name} />
                </div>
              ))}
            </div>
          </div>
        ) : result ? (
          <div className="space-y-8 animate-fade-in">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-2xl font-bold">Results</h3>
                <p className="text-sm text-neutral-500">Five unique interpretations generated by {result.provider}.</p>
              </div>
              <button
                onClick={handleClearAndNew}
                className="flex items-center gap-2 px-4 py-2 bg-neutral-100 text-neutral-900 rounded-xl text-sm font-medium hover:bg-neutral-200 transition-colors"
              >
                <RefreshCw className="w-4 h-4" />
                <span>New Generation</span>
              </button>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {result.variations.map((variation) => (
                <div key={variation.id} className="h-[600px]">
                  <ComponentPreview variation={variation} />
                </div>
              ))}
            </div>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 opacity-20 grayscale pointer-events-none">
            {loadingVariations.map((v) => (
              <div key={v.id} className="h-[400px]">
                <div className="w-full h-full bg-neutral-100 rounded-3xl border border-neutral-200" />
              </div>
            ))}
          </div>
        )}
      </div>
      
      {/* Input Area */}
      <div className="fixed bottom-8 left-1/2 -translate-x-1/2 w-full max-w-3xl px-6 z-50">
        <div className="bg-white/80 backdrop-blur-xl border border-neutral-200 rounded-[2rem] p-2 shadow-2xl">
          {error && (
            <div className="mx-4 mb-2 p-3 bg-red-50 rounded-2xl text-xs text-red-600 flex items-center justify-between">
              <span className="flex items-center gap-2">
                <AlertCircle className="w-3.5 h-3.5" />
                {error}
              </span>
              <button onClick={clearError} className="p-1 hover:bg-red-100 rounded-lg">✕</button>
            </div>
          )}
          
          <div className="flex items-center gap-2">
            <textarea
              value={instruction}
              onChange={(e) => setInstruction(e.target.value.slice(0, maxChars))}
              onKeyDown={handleKeyPress}
              placeholder="Describe what you want to build..."
              className="flex-1 bg-transparent border-none focus:ring-0 px-4 py-3 text-sm resize-none min-h-[50px] max-h-[150px]"
              disabled={loading}
              rows={1}
            />
            
            <button
              onClick={handleGenerateClick}
              disabled={loading || !instruction.trim()}
              className="h-12 w-12 flex items-center justify-center bg-neutral-900 text-white rounded-full hover:bg-neutral-800 transition-all disabled:opacity-30 disabled:grayscale"
            >
              {loading ? <div className="spinner !w-4 !h-4" /> : <Wand2 className="w-5 h-5" />}
            </button>
          </div>
          <div className="px-4 pb-2 flex justify-between items-center">
            <span className="text-[10px] text-neutral-400 font-medium">
              Press {navigator.platform.includes('Mac') ? '⌘' : 'Ctrl'} + Enter to generate
            </span>
            <span className={`text-[10px] font-medium ${charCount > maxChars * 0.9 ? 'text-red-500' : 'text-neutral-400'}`}>
              {charCount}/{maxChars}
            </span>
          </div>
        </div>
      </div>
    </div>
  )
}
